---
all:
  hosts:
    jenkins:
      ansible_host: ${jenkins_instance_public_ip}  # Auto-generated by Terraform
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ${key_file_path}
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

